/**
 * CarbonPilot Shared Enums
 * Source of truth for entity types, workflows, and states.
 */

export enum UserRole {
  CUSTOMER_ADMIN = 'CUSTOMER_ADMIN',
  PROCUREMENT_MANAGER = 'PROCUREMENT_MANAGER',
  SUSTAINABILITY_MANAGER = 'SUSTAINABILITY_MANAGER',
  SUPPLIER_ADMIN = 'SUPPLIER_ADMIN',
  DATA_CONTRIBUTOR = 'DATA_CONTRIBUTOR',
}

export enum OrganizationType {
  CUSTOMER = 'CUSTOMER',
  SUPPLIER = 'SUPPLIER',
}

export function organizationTypeForRole(role: UserRole): OrganizationType | undefined {
  switch (role) {
    case UserRole.CUSTOMER_ADMIN:
    case UserRole.PROCUREMENT_MANAGER:
    case UserRole.SUSTAINABILITY_MANAGER:
      return OrganizationType.CUSTOMER;
    case UserRole.SUPPLIER_ADMIN:
    case UserRole.DATA_CONTRIBUTOR:
      return OrganizationType.SUPPLIER;
    default:
      return undefined;
  }
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INVITED = 'INVITED',
  SUSPENDED = 'SUSPENDED',
}

export enum OrganizationStatus {
  ACTIVE = 'ACTIVE',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
  INACTIVE = 'INACTIVE',
}

export enum SupplierStatus {
  INVITED = 'INVITED',
  ACTIVE = 'ACTIVE',
  PENDING = 'PENDING',
  INACTIVE = 'INACTIVE',
  TERMINATED = 'TERMINATED',
}

export enum ProductStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export const PRODUCT_UNITS = [
  'kg',
  'ton',
  'gram',
  'liter',
  'piece',
  'unit',
  'meter',
  'square_meter',
  'cubic_meter',
] as const;

export enum DocumentType {
  PCF = 'PCF', // Product Carbon Footprint
  PCF_REPORT = 'PCF_REPORT',
  EPD = 'EPD', // Environmental Product Declaration
  LCA_REPORT = 'LCA_REPORT',
  GHG_INVENTORY = 'GHG_INVENTORY',
  ENERGY_BILL = 'ENERGY_BILL',
  FUEL_RECORD = 'FUEL_RECORD',
  ISO_CERTIFICATE = 'ISO_CERTIFICATE',
  RECYCLED_CONTENT_CERTIFICATE = 'RECYCLED_CONTENT_CERTIFICATE',
  ENVIRONMENTAL_POLICY = 'ENVIRONMENTAL_POLICY',
  PRODUCT_SPECIFICATION = 'PRODUCT_SPECIFICATION',
  INVOICE = 'INVOICE',
  PURCHASE_ORDER = 'PURCHASE_ORDER',
  CERTIFICATE = 'CERTIFICATE',
  ENERGY_REPORT = 'ENERGY_REPORT',
  SUSTAINABILITY_REPORT = 'SUSTAINABILITY_REPORT',
  DECLARATION = 'DECLARATION',
  LAB_REPORT = 'LAB_REPORT',
  OTHER = 'OTHER',
}

export enum DocumentStatus {
  UPLOADED = 'UPLOADED',
  PROCESSING = 'PROCESSING',
  EXTRACTED = 'EXTRACTED',
  NEEDS_REVIEW = 'NEEDS_REVIEW',
  IMPORTED = 'IMPORTED',
  FAILED = 'FAILED',
  ARCHIVED = 'ARCHIVED',
}

export enum DocumentClassificationSource {
  SUPPLIER_DECLARED = 'SUPPLIER_DECLARED',
  AI = 'AI',
  MANUAL = 'MANUAL',
}

export enum ClaimStatus {
  EXTRACTED = 'EXTRACTED',
  SUPPORTED = 'SUPPORTED',
  PARTIALLY_SUPPORTED = 'PARTIALLY_SUPPORTED',
  UNSUPPORTED = 'UNSUPPORTED',
  NEEDS_REVIEW = 'NEEDS_REVIEW',
  INCONSISTENT = 'INCONSISTENT',
  CORROBORATED = 'CORROBORATED',
  PENDING = 'PENDING',
}

export enum VerificationStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  VERIFIED = 'VERIFIED',
  FLAGGED = 'FLAGGED',
  FAILED = 'FAILED',
}

export enum EvidenceCheckType {
  SUPPLIER_MATCH = 'SUPPLIER_MATCH',
  PRODUCT_MATCH = 'PRODUCT_MATCH',
  FACILITY_MATCH = 'FACILITY_MATCH',
  PERIOD_MATCH = 'PERIOD_MATCH',
  METHODOLOGY_CHECK = 'METHODOLOGY_CHECK',
  BOUNDARY_CHECK = 'BOUNDARY_CHECK',
  QUANTITY_MATCH = 'QUANTITY_MATCH',
  CERTIFICATE_VALIDITY = 'CERTIFICATE_VALIDITY',
  INVOICE_MATCH = 'INVOICE_MATCH',
  THIRD_PARTY_VERIFICATION = 'THIRD_PARTY_VERIFICATION',
  CROSS_DOCUMENT_CONSISTENCY = 'CROSS_DOCUMENT_CONSISTENCY',
}

export enum EvidenceCheckResult {
  PASS = 'PASS',
  FAIL = 'FAIL',
  UNKNOWN = 'UNKNOWN',
}

export enum AnomalyType {
  MISSING_EVIDENCE = 'MISSING_EVIDENCE',
  EXTRACTION_FAILURE = 'EXTRACTION_FAILURE',
  INVALID_VALUE = 'INVALID_VALUE',
  UNIT_MISMATCH = 'UNIT_MISMATCH',
  CROSS_DOCUMENT_CONTRADICTION = 'CROSS_DOCUMENT_CONTRADICTION',
  CORROBORATION_MISMATCH = 'CORROBORATION_MISMATCH',
  QUANTITY_MISMATCH = 'QUANTITY_MISMATCH',
  PRODUCT_MISMATCH = 'PRODUCT_MISMATCH',
  FACILITY_MISMATCH = 'FACILITY_MISMATCH',
  DATE_MISMATCH = 'DATE_MISMATCH',
  CERTIFICATE_EXPIRED = 'CERTIFICATE_EXPIRED',
  CERTIFICATE_MISMATCH = 'CERTIFICATE_MISMATCH',
  DUPLICATE_EVIDENCE = 'DUPLICATE_EVIDENCE',
  MISSING_BOUNDARY = 'MISSING_BOUNDARY',
  MISSING_METHODOLOGY = 'MISSING_METHODOLOGY',
  UNSUPPORTED_CLAIM = 'UNSUPPORTED_CLAIM',
}

export enum AnomalySeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum AnomalyStatus {
  OPEN = 'OPEN',
  UNDER_REVIEW = 'UNDER_REVIEW',
  RESOLVED = 'RESOLVED',
  IGNORED = 'IGNORED',
}

export enum CertificateStatus {
  VALID = 'VALID',
  EXPIRING_SOON = 'EXPIRING_SOON',
  EXPIRED = 'EXPIRED',
  INVALID = 'INVALID',
  PENDING = 'PENDING',
}

export enum DataRequestStatus {
  DRAFT = 'DRAFT',
  SENT = 'SENT',
  IN_PROGRESS = 'IN_PROGRESS',
  SUBMITTED = 'SUBMITTED',
  NEEDS_CLARIFICATION = 'NEEDS_CLARIFICATION',
  IN_REVIEW = 'IN_REVIEW',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum DataRequestResponseType {
  DOCUMENT = 'DOCUMENT',
  TEXT = 'TEXT',
  NUMBER = 'NUMBER',
  DECIMAL = 'DECIMAL',
  DATE = 'DATE',
  YES_NO = 'YES_NO',
  BOOLEAN = 'BOOLEAN',
  SINGLE_SELECT = 'SINGLE_SELECT',
  MULTI_SELECT = 'MULTI_SELECT',
}

export enum QuestionnaireCategory {
  PRODUCT = 'PRODUCT',
  CARBON = 'CARBON',
  ENERGY = 'ENERGY',
  MATERIAL = 'MATERIAL',
  WASTE = 'WASTE',
  WATER = 'WATER',
  CERTIFICATION = 'CERTIFICATION',
  RENEWABLE_ENERGY = 'RENEWABLE_ENERGY',
  SUPPLY_CHAIN = 'SUPPLY_CHAIN',
  GENERAL_SUSTAINABILITY = 'GENERAL_SUSTAINABILITY',
}

export enum QuestionResponseStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
}

export enum PurchaseStatus {
  DRAFT = 'DRAFT',
  CONFIRMED = 'CONFIRMED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  PENDING = 'PENDING',
  DELIVERED = 'DELIVERED',
}

export enum ExtractionStatus {
  PENDING = 'PENDING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
}

export enum EvidencePackStatus {
  DRAFT = 'DRAFT',
  GENERATING = 'GENERATING',
  READY = 'READY',
  FAILED = 'FAILED',
}

export enum CarbonCalculationStatus {
  PENDING = 'PENDING',
  CALCULATED = 'CALCULATED',
  BLOCKED = 'BLOCKED',
}

export enum ComparisonStatus {
  COMPARABLE = 'COMPARABLE',
  NOT_DIRECTLY_COMPARABLE = 'NOT_DIRECTLY_COMPARABLE',
  BLOCKED = 'BLOCKED',
}

export enum ProcurementDecisionStatus {
  DRAFT = 'DRAFT',
  UNDER_REVIEW = 'UNDER_REVIEW',
  DECIDED = 'DECIDED',
  CANCELLED = 'CANCELLED',
}
