/**
 * CarbonPilot Shared Enums
 * Source of truth for entity types, workflows, and states.
 */

export enum UserRole {
  CUSTOMER_ADMIN = 'CUSTOMER_ADMIN',
  PROCUREMENT_MANAGER = 'PROCUREMENT_MANAGER',
  SUSTAINABILITY_MANAGER = 'SUSTAINABILITY_MANAGER',
  SUPPLIER_ADMIN = 'SUPPLIER_ADMIN',
  DATA_CONTRIBUTOR = 'DATA_CONTRIBUTOR',
}

export enum OrganizationType {
  CUSTOMER = 'CUSTOMER',
  SUPPLIER = 'SUPPLIER',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INVITED = 'INVITED',
  SUSPENDED = 'SUSPENDED',
}

export enum OrganizationStatus {
  ACTIVE = 'ACTIVE',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
  INACTIVE = 'INACTIVE',
}

export enum SupplierStatus {
  INVITED = 'INVITED',
  ACTIVE = 'ACTIVE',
  PENDING = 'PENDING',
  INACTIVE = 'INACTIVE',
  TERMINATED = 'TERMINATED',
}

export enum ProductStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum DocumentType {
  PCF = 'PCF', // Product Carbon Footprint
  EPD = 'EPD', // Environmental Product Declaration
  INVOICE = 'INVOICE',
  PURCHASE_ORDER = 'PURCHASE_ORDER',
  CERTIFICATE = 'CERTIFICATE',
  ENERGY_REPORT = 'ENERGY_REPORT',
  SUSTAINABILITY_REPORT = 'SUSTAINABILITY_REPORT',
  DECLARATION = 'DECLARATION',
  LAB_REPORT = 'LAB_REPORT',
  OTHER = 'OTHER',
}

export enum DocumentStatus {
  UPLOADED = 'UPLOADED',
  PROCESSING = 'PROCESSING',
  EXTRACTED = 'EXTRACTED',
  FAILED = 'FAILED',
  ARCHIVED = 'ARCHIVED',
}

export enum ClaimStatus {
  SUPPORTED = 'SUPPORTED',
  PARTIALLY_SUPPORTED = 'PARTIALLY_SUPPORTED',
  UNSUPPORTED = 'UNSUPPORTED',
  PENDING = 'PENDING',
}

export enum VerificationStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  VERIFIED = 'VERIFIED',
  FLAGGED = 'FLAGGED',
  FAILED = 'FAILED',
}

export enum EvidenceCheckType {
  SUPPLIER_MATCH = 'SUPPLIER_MATCH',
  PRODUCT_MATCH = 'PRODUCT_MATCH',
  FACILITY_MATCH = 'FACILITY_MATCH',
  PERIOD_MATCH = 'PERIOD_MATCH',
  METHODOLOGY_CHECK = 'METHODOLOGY_CHECK',
  BOUNDARY_CHECK = 'BOUNDARY_CHECK',
  QUANTITY_MATCH = 'QUANTITY_MATCH',
  CERTIFICATE_VALIDITY = 'CERTIFICATE_VALIDITY',
  INVOICE_MATCH = 'INVOICE_MATCH',
  THIRD_PARTY_VERIFICATION = 'THIRD_PARTY_VERIFICATION',
}

export enum EvidenceCheckResult {
  PASS = 'PASS',
  FAIL = 'FAIL',
  UNKNOWN = 'UNKNOWN',
}

export enum AnomalyType {
  QUANTITY_MISMATCH = 'QUANTITY_MISMATCH',
  PRODUCT_MISMATCH = 'PRODUCT_MISMATCH',
  FACILITY_MISMATCH = 'FACILITY_MISMATCH',
  DATE_MISMATCH = 'DATE_MISMATCH',
  CERTIFICATE_EXPIRED = 'CERTIFICATE_EXPIRED',
  CERTIFICATE_MISMATCH = 'CERTIFICATE_MISMATCH',
  DUPLICATE_EVIDENCE = 'DUPLICATE_EVIDENCE',
  MISSING_BOUNDARY = 'MISSING_BOUNDARY',
  MISSING_METHODOLOGY = 'MISSING_METHODOLOGY',
  UNSUPPORTED_CLAIM = 'UNSUPPORTED_CLAIM',
}

export enum AnomalySeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum AnomalyStatus {
  OPEN = 'OPEN',
  UNDER_REVIEW = 'UNDER_REVIEW',
  RESOLVED = 'RESOLVED',
  IGNORED = 'IGNORED',
}

export enum CertificateStatus {
  VALID = 'VALID',
  EXPIRING_SOON = 'EXPIRING_SOON',
  EXPIRED = 'EXPIRED',
  INVALID = 'INVALID',
  PENDING = 'PENDING',
}

export enum DataRequestStatus {
  DRAFT = 'DRAFT',
  SENT = 'SENT',
  IN_REVIEW = 'IN_REVIEW',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum QuestionResponseStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
}

export enum PurchaseStatus {
  DRAFT = 'DRAFT',
  CONFIRMED = 'CONFIRMED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  PENDING = 'PENDING',
  DELIVERED = 'DELIVERED',
}

export enum ExtractionStatus {
  PENDING = 'PENDING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
}

export enum EvidencePackStatus {
  DRAFT = 'DRAFT',
  GENERATING = 'GENERATING',
  READY = 'READY',
  FAILED = 'FAILED',
}
